### PR TITLE
Fix usages of 'default' as reserved word

### PR DESCRIPTION
**Pull request by kimarre**
This fixes the JSSyntaxTest for the lory source by properly using
'default' since it's a reserved word

### CODE REVIEW

**Comment by solflare** [comment]
CR :moon:

**Comment by danielbeardsley** [comment]
Good job @kimarre !

CR 👍  (though let's wait on our syntax test passing)

**Comment by danielbeardsley** [comment]
Can you open a pull on the upstream repo too?

**Comment by kimarre** [comment]
Oh, yes, I did that [here](https://github.com/meandmax/lory/pull/517).

**Comment by kimarre** [comment]
@danielbeardsley: Should this PR be closed since the mobile indicators one was based on the changes here and it merged?

**Comment by danielbeardsley** [comment]
Not closed, but merged :-)

**Pull request closed without merging**
